[package]
name = "niliter"
version = "0.1.0"
authors = ["Bernhard Schuster <bernhard@ahoi.io>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "An iterator which always returns None"
keywords = ["iterator","helper"]

[dependencies]
